[package]
name = "bibicode"
version = "0.1.2"
authors = ["Florent Jugla <florent@jugla.name>"]
license = "MIT"
description = "A crate to convert any integer from one numeral system to another."
readme="README.md"

[dependencies]
clap = { version = "2.32.0", features = ["yaml"] }
